parameters:
#    nms_cafe.example.class: Nms\CafeBundle\Example

services:
#    nms_cafe.example:
#        class: %nms_cafe.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
