<?php

namespace Nms\CafeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MealRepository extends EntityRepository
{
}
