<?php

namespace Boheme\CafeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenugroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenugroupRepository extends EntityRepository
{
}
