<?php

namespace Boheme\CafeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WineRepository extends EntityRepository
{
    public function filteredFind($sort = "m.id", $direction = "ASC", $filterField = null, $filterVal = null)
    {

        $q = $this->createQueryBuilder('w')
            ->select('w')
            ->orderBy($sort, $direction);
        if (!empty($filterField)) {
            $q->add('where', $filterField . ' LIKE  ?1')
                ->setParameter(1, '%' . $filterVal . '%');
        }
        return $q->getQuery()->getResult();
    }

}
