<?php

namespace Boheme\CafeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WineRepository extends EntityRepository
{
    public function filteredFind($sort = "m.id", $direction = "ASC", $filterField = null, $filterVal = null)
    {

        $q = $this->createQueryBuilder('w')
            ->select('w')
            ->orderBy($sort, $direction);
        if (!empty($filterField)) {
            $q->add('where', $filterField . ' LIKE  ?1')
                ->setParameter(1, '%' . $filterVal . '%');
        }
        return $q->getQuery()->getResult();
    }

    public function winelist() {
//        $q = $this->createQueryBuilder('m')
//                ->select('m')
//                ->where('m.publish <= CURRENT_DATE()')
//                ->orderBy('m.sitting.title', 'ASC');
//        return $q->getQuery()->getResult();

        $query = $this->getEntityManager()->createQuery('SELECT w,v,r FROM BohemeCafeBundle:Wine w '
                . 'JOIN w.variety v '
                . 'JOIN w.region r '
            );
//        $query-> $query->setParameter(1, 'CURRENT_DATE()');
        return $query->getResult();
    }
}
