<?php

namespace Nms\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository {

    public function filteredFind($sort = "m.id", $direction = "ASC", $filterField = null, $filterVal = null) {

        $q = $this->createQueryBuilder('m')
            ->select('m')
            ->orderBy($sort, $direction);
        if (!empty($filterField)) {
            $q->add('where', $filterField . ' LIKE  ?1')
                ->setParameter(1, '%' . $filterVal . '%');
        }

        return $q->getQuery()->getResult();
    }

    public function getChildren($parent = 0) {

        $query = "SELECT * from menus where parent = $parent order by seq";

//        echo $query.'<br>';

        $result = $this->getEntityManager()->getConnection()->executeQuery($query)->fetchAll();
        return $result;
    }

}
